name: cuid2
description: A dart implementaion of the secure, collision-resistant ids optimized for horizontal scaling and performance (v2).
version: 4.0.0
homepage: https://github.com/obsidiaHQ/cuid2
repository: https://github.com/obsidiaHQ/cuid2

environment:
  sdk: ">=3.0.0 <4.0.0"

executables: 
  cuid2:

dependencies:
  pointycastle: ^3.9.1
  web: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
